### ISSUE TITLE
MoppyDesk doesn't see Arduino via USB on Linux

### ISSUE THREAD

**Issue by AmEv7Fam** [samphonic/MoppyClassic#11]
I compiled both the Java and Arduino pieces of code in Linux, and got the Arduino code installed just fine. MoppyDesk came up, but all that's coming up﻿ is "/dev/ttyS0".

'lsusb" brings up "2341:0043", and "ls /dev/tty*" brings up "/dev/ttyACM0".

Thing is, the Arduino development software brings up both "/dev/ttyS0" and "/dev/ACM0"

Again, "/dev/ttyS0" is the motherboard's  onboard serial port, and "/dev/ttyACM0" is the Arduino USB-serial adapter.

**Comment by AmEv7Fam** [comment]
Figured it out!

Place the RXTXCOMM.jar from the Arduino IDE, and place it in the MoppyDesk IDE!

Sammy1Am, could you grab that RXTXComm instead and place it in your code? Arduino seems to have figured out that bug!

**Comment by samphonic** [comment]
Ooo, interesting.  I'll have to look into it.  There's generally two parts to the RXTXCOMM drivers, there's the .jar package, and some dlls/native code.  I wonder what Arduino is using for the native code... definitely going to look at it though.  Thanks again.

**Comment by sparklini** [comment]
i'm having the same problem. I've located the RXTXComm file in the arduino/lib folder. 

Where/how do I put it into the MoppyDesk IDE (I'm using NetBeans)?

**Comment by samphonic** [comment]
You'll need to make sure that it's on your classpath.  You can configure that for the NetBeans project specifically to add that jar, or you can copy that jar into your project folder and add it that way.  (Sorry those aren't more specific, it's been a while since I've been in NetBeans.  Google should be able to help with "add jar to classpath in NetBeans".

**Comment by sparklini** [comment]
Thanks for responding,


Turns out no special effort is needed to run on the Raspberry Pi.

The confusion was when trying to run MoppySim.



On another note,


I've added to your program to allow the drum track to be played on relays and contactors.

Using three pins on the Arduino and a shift register, 8 relays (potentially as many as you wanted I suppose) are connected and create a "click" when they change state.

The nice part about it is there is no need to edit the midi file to make the drum track work. Common drum sounds are pre assigned to the first few relays and any additional are assigned as they occur.


You can see it here on Instagram (Sorry about the LEGO, my kid thought there should be more "Dancing")


https://www.instagram.com/p/BDHjwNFlTeK/?taken-by=sparklini&hl=en

[https://scontent-iad3-1.cdninstagram.com/t51.2885-15/e15/12818895_1039253946133334_2043685906_n.jpg?ig_cache_key=MTIwOTA5MjI2OTE4NzM0ODM2Mg%3D%3D.2]<https://www.instagram.com/p/BDHjwNFlTeK/?taken-by=sparklini&hl=en>

Instagram video by Stephen Carlini * Mar 19, 2016 at 2:37am UTC<https://www.instagram.com/p/BDHjwNFlTeK/?taken-by=sparklini&hl=en>
www.instagram.com
See this Instagram video by @sparklini * 17 likes

https://www.instagram.com/p/BPlHXqfDaAr/?taken-by=sparklini&hl=en

[https://ig-s-a-a.akamaihd.net/hphotos-ak-xfa1/t51.2885-15/s640x640/e15/16110978_1826568164270272_6609444928940408832_n.jpg?ig_cache_key=MTQzMzU4NDQ2ODg3OTA1NjkzOQ%3D%3D.2]<https://www.instagram.com/p/BPlHXqfDaAr/?taken-by=sparklini&hl=en>

Instagram video by Stephen Carlini * Jan 22, 2017 at 8:23pm UTC<https://www.instagram.com/p/BPlHXqfDaAr/?taken-by=sparklini&hl=en>
www.instagram.com
See this Instagram video by @sparklini * 22 likes






I'll try to get it on Github at some point. I'm an Electrician, not a programer so a lot of this is all new to me.


All the best and thanks for putting this together. It has inspired a new hobby for me.


Sparklini




________________________________

**Comment by samphonic** [comment]
> I'm an Electrician, not a programer

Ah, okay, well that answers my question about how you acquired such a varied array of relay switches =P  And actually, I'm inclined to agree with your kid; the dancing definitely adds more excitement to the whole thing!

Also, the relays sound awesome!  Definitely get that code up here when you get a chance, I think it'd be a fun addition.  I'd want to make sure it was configurable/optional so people without the relays wouldn't be confused (I've tried to keep the learning curve for setting up a new project low), but I think a lot of people would enjoy this.

**Comment by sparklini** [comment]
I agree that it should be a configurable option. The biggest problem I seem to encounter is assigning the large number of drum sounds (or notes) to a small number of relays.

My first solution was to group like sounds. For example there are multiple kick drum sounds. This works well on most songs but not always.

I also played with another set up that assigns the relays to drum sounds as they occur in the song. Nothing got missed but sometimes the ride cymbal gets assigned to a giant motor contactor and the whole thing starts jumping off the table!

Current set up combines both ideas but that can be looked at later.

Can you help me with the next step?  I've gone through the code, cleaned it up and did some commenting. I also wrote up an introduction of sorts.

How do I put it up on Github? I have an account but I'm not 100% sure what to do. (Electrician not programer). Can you point me in the right direction?  I'm sure I can manage from there.




Sent from my Bell Samsung device over Canada's largest network.


-------- Original message --------

**Comment by samphonic** [comment]
Yeah, it does feel like assigning the relays to particular instruments would have to sort of be done per-setup.  It would be nice if the percussion notes had already been grouped into like "low drums", "high drums", "cymbals", but they're all over the place.

So, the GitHub-iest way to get your changes up here is something along the lines of:

1. Back up your current code.  (You should be able to follow the next steps without overwriting it, but I'd hate to have something disappear on you)
2. Click the "fork" button on the top right (this will copy the current code into your own @sparklini repository.
3. If you don't have it already, download the GitHub client, and checkout your fork onto your machine.
4. Now you'll make modifications to the code that GitHub checked out, and then commit those modifications back to your repository (using the GitHub client).  In your particular case, since you've made most of your modifications already, you can probably just overwrite the appropriate files with your modified versions and git should automatically pick up the differences from the current code.
5. After you've checked in your code (and synced to GitHub), your code will be available on github.com under your username.  From here you can submit a pull-request to request that your changes be pulled into my repository.

Before you send the pull request, if you wanna send me a link to your code I can take a look and complain-- err, make suggestions ;P before the pull request that might be a little easier.

**Comment by sparklini** [comment]
Well that all makes sense and seems to have worked. When I log onto my GitHub account and go to "Your Repositories" it does show that it's been updated. So

I guess it worked!?

Not sure what the best way to link the files to you. The more I get into this the more shocked I am about how much computing has changed in the last 15 years. (And now I'm realizing how long 15 years is and feeling more dumb than shocked.)

I've attached the files here. Take a look and tell me what you think. I wanted to alter the code as little as possible to make it simple to compare. There are a number of other things I would like to change to make the program more "Universal" but I figured it would also make it more complicated to review and debug. Thanks for all the help.

Stephen

________________________________

**Comment by samphonic** [comment]
Huh, it didn't... quite work for some reason...  It's showing the modified files as entirely new on the diff pages (all green and all red) instead of showing the line-by-line changes (ideally any lines that didn't change wouldn't be highlighted and it would show just the changes...  It's only two files so I can probably still read through, but it's a bit weird.

And speaking of weird, yeah, computing has changed a lot in 15 years, but git especially took a while for me to wrap my head around even compared to subversion from just a few years back.

Edit again: actually there's only two files so I should able to figure out what's different.  I'll try to take a look tonight.

**Comment by sparklini** [comment]
Ya I saw that too. I'll try forking it again and making the changes when I have some time and I'll put some sort of explication together when I get a chance. I'm also pretty deep into a motorcycle rebuild and parenting two boys so, no rush.

I appreciate your time and help with this.

I'll touch base again when I've made some more progress.

- s


Sent from my Bell Samsung device over Canada's largest network.


-------- Original message --------
