### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by cookins** [samphonic/MoppyClassic#130]
Hi
Question in next
Is there possible to launch netbeans moppy in Android? I want to play floppy music from my Android device. Thanks.

**Comment by solidsnake745** [comment]
Moppy is a Java application. If you can run a Java application in Android, then you can theoretically run Moppy out of an Android device. However I'm not sure how well it will translate over. You'll have to implement this yourself.

**Comment by samphonic** [comment]
You'll need to recompile the application using suitable Andriod serial libraries, and probably need to adapt the UI to something that Android likes.

You may have some luck looking into forks of this project on GitHub that are either ports to Android, or to a command-line version (since that would at least save you the UI trouble).

**Comment by Lynnden42** [comment]
hey just asking this before i go out to try and do it myself. Has this been done? and if so can someone send me the file for it? it'd be so much easier for me to just put it on my phone rather than carrying around a laptop on top of my setup.

**Comment by samphonic** [comment]
I haven't actually heard back from anyone who's done it successfully, but I know a lot of people have expressed an interest.  Check out the forks of this repo to see if anyone made any progress; it's definitely possible.  If you do get it done, let us know here so we can point everyone else to your work :)
