### ISSUE TITLE
Drive Number 5 tries to go to far back. (dual arduino setup)

### ISSUE THREAD

**Issue by HammiKnuff** [samphonic/MoppyClassic#148]
Drive Number 5 tries to go to far back.
only in Songs, Reset is okay

**Comment by samphonic** [comment]
So there are a few potential causes for this, but I don't think it's anything inherently wrong with the software:
* In my experience it's fairly normal for the drives to drop a step here or there, which will cause the Arduino to think the drive is in a different position than it actually is.  Because the default number of steps is just shy of the maximum tracks, it's more likely that this will cause the drive to try to go too far back rather than too far forward (but both are possible).
* If you notice the issue with a single drive consistently (across many different songs), it's possible the drive itself is either somehow faulty, or doesn't keep up with higher notes as well as the other drives.
* It's also possible that that particular drive only supports older 40 track floppies; if that's the case, you'll want to change the MAX_POSITION for that drive to 78 instead of 158.
* There's a slim chance (I'd have to read through the code again to be sure) that depending on how notes stop and start that the code is losing a step (if, for example, the pin is high when the note ends, it may get set to low without correctly tracking the drive's position, which may cause the drive to step one additional time)

It shouldn't cause any major issues (aside from an occasional *clack* sound); most drives seem to just stop moving if they go all the way back.  There's a couple options you could try for mitigating the issue though:
* You can lower the MAX_POSITION value for your drive number 5.  This might provide enough buffer on both sides that you don't notice it as much (depending on how frequently it occurs though, this might not help much.
* If it's just that particular drive, you could try making sure that you send it lower notes.  Lower notes require less frequent steps, which might make that drive happier.
* If it *is* a code issue, using the togglePin function to set high pins back to low on a note-off event should correctly track the position, but even with that there's no guarantee the drive won't skip around a bit.

Hope that helps.  Closing this as a non-issue, but feel free to continue to comment if you have results or questions.
