### ISSUE TITLE
Unable to compile moppy

### ISSUE THREAD

**Issue by Texy** [samphonic/MoppyClassic#2]
Hi,
I,ve copied the rxtxSerial.dll file to the java/ire7/bin folder, but I,m still getting a rxtsSerial related error on my Win XP Pro PC 

"compile:
run:
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
    at java.lang.Runtime.loadLibrary0(Runtime.java:845)
    at java.lang.System.loadLibrary(System.java:1084)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
    at moppydesk.MoppyMainWindow.updateComSelectionMenu(MoppyMainWindow.java:56)
    at moppydesk.MoppyMainWindow.<init>(MoppyMainWindow.java:43)
    at moppydesk.MoppyUI.startup(MoppyUI.java:19)
    at org.jdesktop.application.Application$1.run(Application.java:171)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:705)
    at java.awt.EventQueue.access$000(EventQueue.java:101)
    at java.awt.EventQueue$3.run(EventQueue.java:666)
    at java.awt.EventQueue$3.run(EventQueue.java:664)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:675)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)"

What am I doing wrong?

Texy

**Comment by samphonic** [comment]
Putting it in that folder _should_ be enough to get Java to find it, but if
Netbeans is using a different Java or different path it may not be checking
that folder.  You can add the following argument to the command line call to
java (or if you're using NetBeans, you can right click on the Project, go to
"Properties", Run, and add that in the "VM Options" section).

 -Djava.library.path=C:\path\to\dir\with\dll

I actually ended up using the NetBeans properties and adding that line
because I had some trouble getting it to find the dll in the jre7/bin
folder.  I think you can also add the jre7/bin folder to your PATH
environment variable, but I feel that the java argument method is cleaner.

Let me know if these still don't work.

**Comment by Texy** [comment]
OK thanks. Some progress, not sure if its working though.

I changed the project path to 
-Djava.library.path=C:\Program Files\NetBeans 7.0.1\bin
and the error regarding rxtsSerial has disappeared, however I now get

Updating property file: C:\Documents and Settings\Ian\My Documents\Java\SammyIAm-Moppy-e7b18aa\Java\MoppyDesk\build\built-jar.properties
compile:
run:
Error: Could not find or load main class Files\NetBeans
Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)

So what should I get now, if its succesful, how do I run the executable and what should I see on the screen?

Cheers,
Texy

**Comment by solidsnake745** [comment]
Are you sure you put all the correct files in their place? There should be three files that need to be copied to your JDK folder.

RXTXcomm.jar
rxtxParallel.dll
rxtxSerial.dll

Just copying the one DLL is not sufficient because it's the JAR file that contains the Java classes that define how to use the DLLs.

The two DLLs do go into Java\jdk1.7.0\jre\bin.
The JAR file goes into Java\jdk1.7.0\jre\lib\ext.

Remember, its the JDK that you want to add these files to. The JDK contains the tools for development. JRE6 and JRE7 are NOT for coding! These folders are compiled versions that allow for Java programs to be executed.

Also make sure you are copying the correct set of DLLs for your operating system. There is a set for 32-bit and a set for 64-bit.

You shouldn't have to change the Java Libary path after that. If I were you, I'd change it back to it's default value, put the files in their proper place, and then try running it.

Sam, you should probably include those instructions in your README as it isn't completely straight forward.

I found the original instructions in \Java\SerialDrivers\rxtx-2.1-7-bins-r2\Windows\ch-rxtx-2.2-20081207-win-x64\Install.txt of Sam's stuff.

Hope this helps.

**Comment by Texy** [comment]
Success!
Many thanks for your help on this.
I do have another problem however.
There are 2 midi files supplied kirbystheme and tetris. Selecting either results in the same tune being played.
I,ll see if I can try some other tunes.

Texy

**Comment by samphonic** [comment]
Thanks again, solidsnake745 for your help here.  When I get time I will update the README as you've suggested.

No idea about the MIDI loading issue.  When I get some free time, I'll definitely be going over the code again and making it a little more robust though.

**Comment by sambsa** [comment]
I am using windows 8.1, 64 bit, I also having the same eroor,
I have configured RXTX as follows for running my application in CMD
Copied rxtxParallel.dll and rxtxSerial.dll inside C:\Program Files\Java\jdk1.8.0_25\jre\bin
Copied RXTXcomm.jar inside C:\Program Files\Java\jdk1.8.0_25\jre\lib\ext

Error is like foolows:

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while
loading gnu.io.RXTXCommDriver
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: no rxtxSerial in
java.library.path
at java.lang.ClassLoader.loadLibrary(Unknown Source)
at java.lang.Runtime.loadLibrary0(Unknown Source)
at java.lang.System.loadLibrary(Unknown Source)

Please help buddys!!

**Comment by MoppyDoppy** [comment]
Please check your java.library.path! 
Please see 

## http://examples.javacodegeeks.com/java-basics/java-library-path-what-is-it-and-how-to-use/

Setting the java.library path. using Netbeans

In order to define the java.library.path property in Netbeans, the following steps must be completed:

```
Select your project in the Projects area and press a right click on it.
Select Properties and then, move to the Run tab.
In the VM Options field, add the following option, based on your library’s path:
java -Djava.library.path=<path_to_dll>

Click on OK in order for the window to close.
```

If the aforementioned steps have been successfully completed, then the selected project will be executed using the required native library.

**Comment by samphonic** [comment]
Thanks, @MoppyDoppy !  That's an excellent link.

**Comment by GeydarP** [comment]
hi
 i`ve installed everything ,but when i run moppy desk i get an error and the window dont pop up
Error: Could not find or load main class moppydesk.MoppyUI
do you have any idea wht whent wrong?
![moppydeskscreen](https://cloud.githubusercontent.com/assets/12262292/7483887/9eb47dec-f38b-11e4-8cc8-b185316c73b9.JPG)

**Comment by samphonic** [comment]
@GeydarP , thanks for posting an image, that makes it so much easier to figure out what's going on.

To start, it looks like you may have somehow got a hold of the older Moppy version.  There should be a lot more packages on the left there.  Try downloading the [.zip file](https://github.com/SammyIAm/Moppy/archive/moppy-advanced.zip) from GitHub again and giving it a shot.

The little red icon on the left indicates that there's an error in MoppyUI.java, so you might want to investigate that if downloading a new copy doesn't fix your issue.

**Comment by GeydarP** [comment]
hi 
i downloaded the new files and installed as before but now i get a lot of diferent errors ,as you noticed i'm really new to arduino and java ,if you can please help me with this the first picture is from the last error i dont think i can deal with it ,the second one is from the error before with the detail of moppyui.java file , it seem to be a minor issue
thank you
![moppydeskscreen1](https://cloud.githubusercontent.com/assets/12262292/7490484/96b5a176-f3e9-11e4-8573-0abc8af2ff6c.JPG)
![moppydeskscreen2](https://cloud.githubusercontent.com/assets/12262292/7490486/9c55a4b4-f3e9-11e4-8e75-e27b93b8c563.JPG)

**Comment by samphonic** [comment]
You'll definitely want to me using the newer version (for all sorts of reasons).  The errors you're getting there seem to be issues with referencing some of the library files (specifically NRJavaSerial).

When you download the .zip file, you should:
1. Unzip it to a folder somewhere.
2. Open NetBeans.
3. Go to File > Open Project... and open the project that shows in the folder you've unzipped from.

If you're doing something like creating a new project from existing source, you may get some of these reference issues.

Something else to check is to make sure that Windows isn't blocking the zip file after you've downloaded it.

**Comment by GeydarP** [comment]
thank you very much it helped 
i`ve opened the project from the unzipped folder directly ,and the window pop up
but the drives dont seem to respond so well some time they play single notes ,some time they just stuck, i think i have wiring problem ,i`ll try to take everythin apart and do it one more time .

**Comment by samphonic** [comment]
Glad you've got things (sort of) working.  Definitely try using some of the included sample MIDI files to start-- other MIDIs may have notes outside the operating range of the drives and won't play as consistently.

**Comment by DinukaShehan** [comment]
![Capture](https://user-images.githubusercontent.com/34016875/65908431-0fe18f80-e3e4-11e9-91d8-0b1f93bece6e.PNG)
please help

**Comment by DinukaShehan** [comment]
init:
Deleting: C:\Users\Dilen\Desktop\MoppyDesk\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\Dilen\Desktop\MoppyDesk\build\built-jar.properties
compile:
run:
java.lang.NoClassDefFoundError: org/jdesktop/application/SingleFrameApplication
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Caused by: java.lang.ClassNotFoundException: org.jdesktop.application.SingleFrameApplication
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 13 more
Exception in thread "main" Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)

**Comment by DinukaShehan** [comment]
this is the error

**Comment by DinukaShehan** [comment]
* To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moppydesk;

import org.jdesktop.application.SingleFrameApplication;

/**
 *
 * @author Sam
 */
public class MoppyUI extends SingleFrameApplication{

    MoppySequencer ms = null;
    
    @Override
    protected void startup() {
        MoppyMainWindow mainWindow = new MoppyMainWindow(this);
        show(mainWindow);
    }
    
     /**
     * Main method launching the application.
     */
    public static void main(String[] args) {
        launch(MoppyUI.class, args);
    }
    
}

**Comment by samphonic** [comment]
This issue has already been closed, but you should be using the [newer version](https://github.com/SammyIAm/Moppy2) of Moppy, rather than this one.

For edification purposes, the error you're getting is because you're missing some NetBeans plugin (can't remember what it is anymore).

**Comment by spr69** [comment]
hello the error that appears to me is the following
![imagen](https://user-images.githubusercontent.com/61925418/76155755-453a8980-60b6-11ea-983e-a72073267459.png)
I would very much appreciate your help, regards!!

**Comment by samphonic** [comment]
@spr69 Please take a look at the comment right above yours, and get the newer version of Moppy.  (These sorts of issues are why this version isn't supported anymore)
