### ISSUE TITLE
Fails when 2 drives are added

### ISSUE THREAD

**Issue by Shoop63** [samphonic/MoppyClassic#29]
Not sure if anyone else is having this problem or not. I am setting up the musical floppy drives for a club project and we are having an issue that whenever two drives are added it fails to play music.  Each drive works independently but when we try to have them play different tracks it does nothing.  We are using the Arduino Mega 2650.  Thanks for any help.

**Comment by samphonic** [comment]
A few additional details might help point toward a solution:
- Are you using Moppy, or MoppyAdvanced
- When you say each drive works independently, do you mean they each work when you hook them up to pins 2 and 3?  Or does the second drive work on pins 4 and 5 only when the first floppy is disconnected?
- When it fails to play music, are there any errors?  Is the RX light on the Arduino blinking when you start playing the MIDI file?

If there aren't any software errors, the RX light is blinking, and both drives fail when they're hooked up, I would tend to suspect it's a wiring / grounding issue.

**Comment by Shoop63** [comment]
We are using MoppyAdvanced.
The drives work in 2 and 3 and also in 3 and 4.
There are no errors that show up and the RX light does blink.

I agree and think its a grounding issue but I'm not too sure on how to go about fixing it.  We have Cat5 ethernet cables for our wiring and I've tried using the copper cable from a Coaxial cable to bring the ground wires together and run them into the arduino.  I think that is my point of failure.

**Comment by samphonic** [comment]
(Hoping you meant 4 and 5 instead of "3 and 4" =P )

My suggestion for the grounding is to run a single wire from the Arduino's GND port, and take the ground wires on the Cat5 coming from the floppy drives and wire-nut them all together (or something similar to get them all connected), rather than try to run a bunch of wires to the Arduino.

Possibly helpful background: the way the floppy drive interface works (or at least my understanding of how it works) is that the even pins are held at 5v by the floppy's internal circuitry.  When they're floating (i.e. not connected to anything) the pin is essentially in the "OFF" state.  When one of the even pins is connected to ground, it's considered "ON".  Because the even numbered pins are connected to the Arduino's outputs, when the Arduino turns a pin "OFF", it brings it to the Arduino's ground level.  If the level of the pin matches the drive's internal ground, then the drive sees it as on.  If the Arduino's ground level is different, or if something is interfering with bringing the even pin to ground, it won't work.

(Apologies to anyone who actually understands circuitry if I butchered that explanation)

**Comment by Shoop63** [comment]
We got it working. It was the ground wire. Thanks for the help.

**Comment by samphonic** [comment]
Not a problem; glad you got it working!  =)
