### ISSUE TITLE
Moppy crashes with SIGSEGV

### ISSUE THREAD

**Issue by meequz** [samphonic/MoppyClassic#32]
Moppy have crashed. I'm grab it via "git clone", compile with NetBeans, open it, load midi (Tetris.mid from samples), mark the first channel, connect to my Arduino Uno (it's on /dev/ttyACM0, but Moppy was only see the /dev/S0, I've created a symlink and give a rw rights to both), choose /dev/S0. Press Play. It's starting to play something about two notes, than crashed. How it was:

```
$ /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -jar MoppyDesk.jar 
Experimental:  JNI_OnLoad called.
Stable Library
=========================================
Native lib Version = RXTX-2.1-7
Java lib Version   = RXTX-2.1-7
Loaded sequence with 3 MIDI channels.
Tempo changed to: 100
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f794d724733, pid=28273, tid=140159003662080
#
# JRE version: 7.0_15-b20
# Java VM: OpenJDK 64-Bit Server VM (23.7-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librxtxSerial.so+0x7733]  Java_gnu_io_RXTXPort_nativeDrain+0xc3
#
# Core dump written. Default location: /media/DATABIG/Downloads/Arduino/from git/Moppy-moppy-advanced/Java/MoppyDesk/dist/core or core.28273
#
# An error report file with more information is saved as:
# /media/DATABIG/Downloads/Arduino/from git/Moppy-moppy-advanced/Java/MoppyDesk/dist/hs_err_pid28273.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-7/
#
Aborted (core dumped)
```

The same with Moppy-advanced and regular Moppy. The same with Java6 and Java7. The same with two different floppies.

I have connect one floppy per time. OS - Ubuntu 12.04 x86_64, Java6 and 7 from repos (openjdk, not oracle). DE - KDE:) NetBeans 7.0.1. RXTXcomm-2.1-7. If you want, I can send the *.log and "core" files to you.

Appreciate for any help. Sorry for my English, my native language is Belarusian.

**Comment by samphonic** [comment]
I appreciate the English as I know exactly zero Belarusian.  =)

Unfortunately, the problem appears to be somewhere in the RXTXcomm libraries, rather than something with the Moppy code, so I can't necessarily fix the issue.  That said, a couple things to try:
- 2.1-7 is the latest stable build of RXTXcomm, but there does appear to be a 2.2 available as a pre-release.  You could try that and see if it makes a difference.
- If you're able to, try installing Sun/Oracle's JDK instead of OpenJDK.  I hate Oracle as much as the next guy, but that might make a difference too.

It shouldn't have anything to do with the floppies themselves, so you're fine there.  There's a _small_ chance it could be something with the Arduino itself, but I doubt it.

Give those a try and let me know how it works out.

**Comment by samphonic** [comment]
Moppy is no longer using the RXTX libraries, so hopefully this issue is resolved.  Try the latest commit.
