### ISSUE TITLE
Unresponsive Drives

### ISSUE THREAD

**Issue by ghost** [samphonic/MoppyClassic#37]
I'm running Mac OSX Mountain Lion and have got everything up and running with the Arduino software and Netbeans and my arduino UNO is connected, but when I load a sequence and click start I get no response from the two drives which I am using. Both drives work - I have tested them - but I get only a constant 'ticking' from one drive and nothing from the other. It may be a grounding problem? I have all my ground wires coming out of a breadboard and into the single GND on the Arduino and when I fiddle with the connection to the ground I do get a tiny bit of movement from both drives.

I feel like I'm almost there but I'm struggling here just to get it all together right at the end.

**Comment by ghost** [comment]
I also have this warning on netbeans "WARNING: unspecified resource Application.id using MoppyUI". And I feel like there is some form of communication between the software and the drives as they sometimes respond to 'reset' commands etc from the Moppy software.

**Comment by Chong-McBong** [comment]
maybe check your ground with a multimeter, to make sure everything is connected properly.. 
(you could send the ground on your power supply directly to your arduino's ground, that will connect all your drives back to the arduino, as they all share a ground anyway, saves stringing an extra cable to each drive.

if one of the drives is clicking sometimes, its probably got its step and direction pins the wrong way round, try reversing pins 18 and 20 and see what happens.. 

it could also be the midi file you are testing with, maybe try some other simple midi files, maybe you will have more luck that way...

it took me a couple of days to get my setup to work when i started, now i have 16 drives connected to 2 arduinos, all singing happily together - just got to be persistent and determined, and double check everything :)

**Comment by samphonic** [comment]
All of Chong's advise is basically everything I'd recommend checking on first.

I just wanted to add though: don't worry about the "WARNING", it's just some weird Swing Framework thing that I never properly sorted out; it won't cause any issues.

Keep at it!

**Comment by ghost** [comment]
Thanks a lot guys. One of my drives now functions. It plays the example songs in the MoppyDesk folder great. My other drive is still completely unresponsive though? I get nothing from it in terms of communicating with the Arduino. 

I swapped 18+20 on my now functioning drive (thanks Chong) and unplugged all my ground jumpers to the arduino and that's when it started functioning. The weird thing is that if I unplug the direction or step pins from the unresponsive drive then my functioning drive stops working?

Nothing is plugged into the GND on the Arduino at the moment...

Thanks for your help - getting there :)

**Comment by samphonic** [comment]
Huh, that _is_ unusual...  

You'll definitely need to have _something_ connected to the GND on your Arduino, or things aren't going to work right.  As Chong suggested, you can try hooking a line from the ground on your power supply to the Arduino, and that should take care of it.  Alternatively, any of the odd-numbered pins on the floppy drive should be ground too.  I suspect that the Arudino might actually be grounding through the "unresponsive drive", which is why when you disconnect it, the first one stops working.

Actually, that gives me another idea.  The pins on the non-functioning drive might be upside down.  Which means you've connected to pins 17 and 19 (both ground pins) instead of 18 and 20.  Try switching those around?

The next thing to try might be switching the drives around.  In other words, try hooking up the second (nonfunctioning) drive to the pins for the first drive, or try hooking the working drive up to the pins for the second one.

Getting close!

**Comment by ghost** [comment]
Okay I'll try the ground from my ATX power supply. Sorry to be a bother, but there are a number of ground pins on the 20 pin connector from the supply... which one(s)?

**Comment by samphonic** [comment]
Not a bother at all.  =)

I am fairly confidant that any black pins on that connector will work just as well.  (Ideally, in theory, all the grounds on the power supply are connected to each other, somehow, and in turn connected to the PS case and the ground pin on the AC supply cord).

**Comment by ghost** [comment]
Got it working, thanks a lot guys! Just a bit of persistence needed haha

**Comment by samphonic** [comment]
Glad you got it working!

**Comment by gustavoem** [comment]
I am also having this problem. I receive this warning when I run de app, and after I try to connect, the programm is closed because of a "fatal error":

'
 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f459b877733, pid=9469, tid=139937795299072  
'

I've tried to use the new version of moppy and I didn't have warnings or errors but it also doesn't work.
I'm using 64bits version of Ubutnu 13.10 and Arduino Duemilanove.
