### ISSUE TITLE
Calculating microPeriods Note Value

### ISSUE THREAD

**Issue by adevriesc** [samphonic/MoppyClassic#38]
I'm attempting to extend the dynamic range of Moppy due to the addition of an amplified hard drive to my array. I found the area of the code that I need to change, but I am unsure what formula to use for determining the note values.

Better - is there a chart of the values somewhere?

(ex. 30578, 28861, 27242, 25713, 24270, 22909, 21622, 20409, 19263, 18182, 17161, 16198, //C1 - B1)

Thanks.

**Comment by samphonic** [comment]
I use this page: http://www.phy.mtu.edu/~suits/notefreqs.html to find the frequencies.

(1/_frequency_) x 10^6 = period in microseconds.

If you're looking to go extreme, each octave doubles the frequency of the note (e.g. C1 = 32.7 Hz, C2 = 65.41 Hz), so you can use that to go beyond the range listed on that site.  Unfortunately by C9, you'll be starting to get a bit out of tune due to rounding to the nearest microsecond.  Probably not going to make a big difference in this case, but worth paying attention to (I didn't use milliseconds because they were too big to accurately play any reasonable musical notes)
