### ISSUE TITLE
Multiple Arduinos

### ISSUE THREAD

**Issue by Photovor** [samphonic/MoppyClassic#4]
I was curious if you've considered any code that would allow multiple Arduinos to work together.  For example, say you want to use 10 or 12 drives, you'd need 2 Arduino Unos.  I could see using something like shift registers to really expand the system, however the arduino code would really have to change.

**Comment by samphonic** [comment]
I have definitely considered both of those options, but haven't actually attempted to implement either of them.

Multiple Arduinos would only require a change in the Java code to send anything over channel 10 (you can get up to 10 drives on an Arduino Uno) to a different COM port, and shifting the pin assignments down by 10 (i.e. channel 11 would appear as channel 10 for the second Arduino).  A second Arduino might also allow connecting a more complex instrument (robotic drumset?), and especially for that reason, I'm strongly considering adding that functionality in the future.

I've also considered shift registers as this would, as you've pointed out, allow the control of a much larger number of devices from a single Arduino.  However, I have some concerns about latency that might be introduced by writing to the shift register.  I suppose if it was consistent it would shift all the pulses evenly, and the pitches would still be correct.

That said though, MIDI is limited to only 16 channels, so the current method of turning MIDIs into information for the drives would break down at that point.  You can play multiple parts/notes on a single channel, but because each drive can only play a single note at a time, you would need to have an algorithm to distribute notes among the drives.  In theory, you could do that right now and rather than assigning a single channel to each drive, just assign one note per drive up to the maximum number of drives.  The downside with this method is that each part of the song will jump around the drives rather than each drive playing its own part.

Shift registers are more likely to work well for instruments that have one switch per pitch (like a xylophone), since you only need to switch the key on (and off for some instruments) rather than continuously pulse the switch at the desired frequency.

A second Arduino would definitely be cool though.  If you're feeling adventurous, grab a copy of the repository and try it out.  =)
