### ISSUE TITLE
rxtx issues on OSX 10.8

### ISSUE THREAD

**Issue by galarant** [samphonic/MoppyClassic#59]
Running into that lovely rxtx bug (i.e. `java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path`) with:

OSX 10.8
JDK 1.7
NetBeans IDE 7.5

I've tried every available binary, even tried building an x64 version from source on my hardware and I'm still getting that bug.

@SammyIAm have you considered any alternatives to rxtx? I'm not a Java developer so I'm not going to try and suggest any alternatives, but IMHO the rxtx dependency is seriously impacting the stability of this otherwise awesome project.

**Comment by samphonic** [comment]
The error you are running into is unrelated to the rxtx binary you are trying to use, but indicates that Java is unable to locate the binary at all.  Depending on your system's configuration, there may be a default folder that it's searching in, but you should also try using the `-Djava.library.path` argument when running Java to specify the folder containing the library.

I haven't considered any alternatives to rxtx because it seems to be fairly widely used, and is consequently well-supported across multiple platforms.  Generally speaking, few people have actually had any issues with rxtx and Moppy.  The issues that _have_ arisen tend to either related to Java not being able to locate the library (a configuration issue, rather than something to do with rxtx itself), or a mismatch between the native library being used and the jar file I've included (unfortunate, but somewhat inevitable since different environments are going to need different native libs).

That said, if anyone has any alternative multi-platform native serial libraries for Java, I always welcome suggestions.

**Comment by samphonic** [comment]
RXTX is no longer used by Moppy.  Try the newer commits.
