### ISSUE TITLE
Moppy over usbmidi, Max/MSP or Pure Data

### ISSUE THREAD

**Issue by HerrPaule** [samphonic/MoppyClassic#61]
I modified your Arduino sketch to use it with Teensy over USBMIDI.
The JAVA RXTX drivers produced some errors on my Mac OSX 10.9, so I checked the bytes which will be send by your MoppyDesk application and paste them to Max/MSP and Pure Data. So you can use Max/MSP or Pure Data as a client. Pure Data works also on the Raspberry Pi with PD-extended and OSC messages. 

more details & codes can be found at my source: https://github.com/HerrPaule/MOPPY-modified

Thanks a lot for your work.

**Comment by GrahamCampbell** [comment]
@HerrPaule. Why did you get rid of all the commit history? You are making it look like it is 100% your work...

**Comment by HerrPaule** [comment]
@GrahamCampbell Which History do you mean. I added some notes at the teensy sketch to make clear, that the original code is based on SammyIAm. Sorry, it wasn't my aim to let it look like my work. If you have any tips or doubts, let me know and I will correct it.

**Comment by GrahamCampbell** [comment]
What I was expecting to see was a git repo with all of the original commits from this repo, then with your work ontop.

**Comment by HerrPaule** [comment]
sorry, I've less experience with Github. How can I fix this or where can I find an explanation?

**Comment by jazzbassNick** [comment]
I think you want to create a branch, but hopefully someone that knows for sure whill chime in.

**Comment by samphonic** [comment]
@HerrPaule I'm a bit new to GitHub myself, but my understanding is that you'd use the "Fork" button on the original repository, and then commit any changes you make into that fork.

I'm less concerned with getting credit for my work (you've done a fine job making it clear that it's based on my code), as I am with making sure it's easy for everyone to see all the changes and forks available so that no one's duplicating work, and everyone can help contribute.
