### ISSUE TITLE
Drives not responsing PLEASE HELP ME FAST!

### ISSUE THREAD

**Issue by MultiDaxio** [samphonic/MoppyClassic#62]
Hi everybody!
I am having an issue with my floppy-arduino-moppy setup. So, the problem is, when i try to launch the song from the Moppy app (I have tried the new version with these checkboxes (btw. can someone explain what are they used for?) on the right, and the older version, where the "Bridge" bookmark says "Not yet. Sorry!") my drive (I am using only one for now) remains silent. I`ve dobule-no, triple-checked my wires and connections, everything looks fine, Arduino is provided with the code from Moppy.ino file. NetBeans works fine too... I have no clue what am I doing wrong. I can mail you some photos of my contraption if it may help. But PLEASE help m fast. I need o make it work to 14th April 2014. 

Thank you so much, and I`m sorry for my lack of knowlede. I am new to this stuff :)

**Comment by samphonic** [comment]
Well fortunately the 14th is a ways off, so hopefully we can get things up and working by then.

To start with, the check boxes in the Moppy Advanced application are to assign MIDI channels (from the MIDI file) to a particular Arduino (just in case you've got multiple).  In your case, since you've only got one drive, you'll just want to check the first box, and make sure that you have the correct COM port selected in the dropdown for that line.

Then we need to check a few things:
- Make sure the MIDI file you are using has notes on MIDI channel 1, in an appropriate range for the floppy drives.  The example MIDI files are a good place to start.
- When you press "Connect" or when you press "Stop/Reset" in the Moppy app, do the drives react at all?
- When you're playing a MIDI file, does the RX light on the Arduino blink in time with the music?
- Double check that the Arduino code successfully compiled and uploaded to the Arduino (the IDE can be pretty quiet about errors sometimes)
- When you manually tap the step/direction pins to a GND wire, does the drive react?
- Is the GND pin of the Arduino connected to a ground pin on the floppy drive?

Run through that list and let me know what you find.  If it's still not working, that should at least help narrow down where the issue is.

**Comment by MultiDaxio** [comment]
Ok, first of all, I am glad, that you have responsed :) 
1) How do you check that?
2) I had a response (a single tick) when I have been clicking Stop/Reset button, but now it does a tick when i plug in - plug out pins from Arduino. Mostly, though, they are silent.
3) Yes, it does.
4) When I am uploading code to the Arduino, no errors pop-up, only if I am using COM 4 while uploading (I have changed that in Moppy app optins too). If I try to upload the code to COM 3 an error pops up (I will post later what does it say, school time:)
5) Yes, it does, so I do not think that drive is broken.
6) Yes, it is. I have grounded pins 17 and 19 to pin GND on Arduino. I have also tried grounding all of the bottom pins of the floppy, nothing happened. Tried grounding only last pin, same thing.
I hope we can figure it out. And thank you, Sammy. I did not expect a respplonse from YOU :)
Thanks!
PS Apologies for my English (I am writing at 7 am, on phone, in a foreign language to me :)

**Comment by MultiDaxio** [comment]
Ok guys, STATUS UPDATE :)
I have talked to my ITC teacher, but she could not think of any solution... But! Today I reassembled the whole contraption, I have reseted Arduino and NetBeans (wipe the code from the existence on my laptop, then download it back) redownloaded Java, replugged all plugs, cleaned out my floppies, changed wires. That, gave me as a result this: I have launched a song, the head moved forward, playing 5-6 notes, reached end of the rail and stopped... To bring it back to begining of the rail I had to pause the song, turn off, then back on ATX. Some progress at least. Might it be a code bug? I did not change anything neither in the code of Moppy.ino nor in the code of MoppyDesk. Am I close? Anybody?
Thanks. Oh, one more. Might that be a processor failiure? I have seen another YT tutorial, and the guy said, that the RXTXcomm are incompatibile with AMD processors (or something like that, I am not an Englishman again, sorry). I am worried about that, because I am not able to get a new laptop in 12 days unfortunately... Is this the cause? Help!

**Comment by samphonic** [comment]
Okay, well that's definitely some good progress!  When you say it plays 5-6 notes, can you tell if they are actual notes from the song that's supposed to be playing?

It sounds like there's an issue with the direction-pin connection from the Arduino to the floppy drive.  When the floppy's direction pin is grounded, the read head will move forward, and when ungrounded (floating) it will move back toward its starting position.

You can try manually disconnecting the direction pin from the drive while it's playing to see if the drive keeps playing notes but moves back in the other direction.

It doesn't sound like a software issue (and this software seems to work for all the other users), and if there were an RXTX issue, you wouldn't be able to communicate with the drive at all, so we can rule that one out as well.

**Comment by MultiDaxio** [comment]
Firstly, I am sooo glad to hear that it is not a RXTX issue. Also I am sure that these notes are from 'Tetris'. I will try make GRD go float manually but tomorrow (it is 10 pm in my country). Thnaks for the support. I will report ASAP. Plus, do you have any further advices?

**Comment by MultiDaxio** [comment]
Sorry misclick :)

**Comment by MultiDaxio** [comment]
STATUS UPDATE #2 
Today I have connected everything back like yesterday, and now I am back to the start. Drive is mute, but I tried to make direction pin float and then it moved forward! I have plugged it back, nothing.
Any ideas wht is it like this? Also, I moved back to the newer version of Moppy Control App.

Experiment #1 
Floated DIR. pin, worknig as said earlier. Song is still playing. Reseted ATX, head is moving a little back, then more notes ar played, but in weird pattern, some are played, some not. Manual GND replugging does nothing.

**Comment by samphonic** [comment]
It sounds like a wiring issue at this point (since the Java app and the Arduino seem to be functioning just fine).  Make sure you have the step pin connected to pin 2 on the Arduino and direction pin connected to pin 3.  There's always a chance that your floppy drive uses a different step or direction pin compared to what I described in the tutorial; though it sounds like you've got the right ones since it seems to work sometimes.

Make sure your connections are really solid, and check that ground connection again.

**Comment by MultiDaxio** [comment]
Checking it right away... Back in 15.

UPDATE: http://www.retrotechnology.com/herbs_stuff/Model4_35_Drives.pdf
I have found here a pin layout for my floppy. Everything is ok. 18 for DIR, plugged in 3 or Arduino, 20 for STEP, plugged in 2 on Arduino. 

Could it be something with the song?
I will check a different wire...

UPDATE #2 
Changed wires, nothing happened...

**Comment by jazzbassNick** [comment]
Is there a functional difference in the GND pins? Wondering if maybe using
the power ground for the drive might be an issue.

**Comment by MultiDaxio** [comment]
I do not understand. You mean that I should ground my drive pins somewhere else?

**Comment by samphonic** [comment]
The most important thing is that the ground pins on the drive are somehow connected to the GND pin on the Arduino.  You can connect them directly to each other, or you can connect both to the ground on the power supply (which effectively connects them to each other).

If the GND on the Arduino is not the same as the ground on the floppy drive, then when the Arduino pulls a pin "low", it might not be the same "low" as the drive, and it won't be detected.

**Comment by MultiDaxio** [comment]
I will post some photos of my contrapiton. Wait a minute.

**Comment by MultiDaxio** [comment]
GitHub does not let me to post the pics. May I e-mail them to you?

**Comment by samphonic** [comment]
Probably easiest if you just uploaded them to a site like [imgur](https://imgur.com/) and posted the link here.  That way it's available with this conversation (and to others like @jazzbassNick ).

**Comment by MultiDaxio** [comment]
OK they are flying to imgur. Just a moment :)

**Comment by MultiDaxio** [comment]
http://imgur.com/iE2nB0l,Mg3j99p,2wlq5fd,CchGZi3,gr7BM9M,VsMLCjE,BIHt8zz,2k3YAsO

Unfortunately imgur messed up the order of these pics. If there is something that you cannot see, just tell me :)

**Comment by jazzbassNick** [comment]
Hard for me to see on my phone, but is the orange connecting below the
yellow or blue? Orange is connected to the correct GND on the arduino.

Also, I'm assuming the green wires are the drive select jumper?

**Comment by MultiDaxio** [comment]
The red (orange) is grounding yellow, and green is indeed drive select

**Comment by MultiDaxio** [comment]
![setup](https://cloud.githubusercontent.com/assets/7130871/2607378/9ecc3a12-bb5c-11e3-89b2-3c662ca71b42.png)
Beautiful version in MS Paint

**Comment by samphonic** [comment]
The MS Paint version was way more helpful actually.  =P

It looks like you might have the even and odd pins backward on the IDE cable.  That is, the yellow and green wires should be where the red and black wires are.  Or to put it a third way, you've got pins 2 & 3 on the Arduino connected to 17&19 instead of 18&20.  

Check out the diagram on the upper right of [this page](http://pinouts.ru/Storage/InternalDisk_pinout.shtml) for the pinout of the cable, and specifically pay attention to the key (little sitcky-outy bit on the side) to make sure it's facing the right way.

**Comment by jazzbassNick** [comment]
Hmmm. Drawing totally helps. Does the led on the drive light up? Usually
when I see wires tied up (like your grounds), I start to wonder if they're
secure. Tried just a single wire from 17 to the arduino?

[image: setup]https://cloud.githubusercontent.com/assets/7130871/2607378/9ecc3a12-bb5c-11e3-89b2-3c662ca71b42.png
Beautiful version in MS Paint

## 

Reply to this email directly or view it on
GitHubhttps://github.com/SammyIAm/Moppy/issues/62#issuecomment-39486253
.

**Comment by MultiDaxio** [comment]
HOLY S@#!T IT WORKS!!!!! IT REALLY WORKS!!!!! HAHAHAHAH! THANK YOU! AHHHH! MAN I COULD NOT SLEEP BECAUSE OF THAT! AAAAAAAAAWWWWWWWWW YYYYYEEEEEEEEAAAAAAAAAHHHHHHHHH! Ahem... Sorry... Anyways, it finally works! Thank you so much for your support Sammy, you too jazzBassNick. I am sooo happy! Really, really thank you! :D:D:D:D :):):) #happiness :)

**Comment by jazzbassNick** [comment]
I found it much easier to use jumper wires directly, female end on the
drive pins, male end in the arduino.

**Comment by jazzbassNick** [comment]
:D Good call Sammy.
Time to get to the real fun ;)

**Comment by MultiDaxio** [comment]
I am going to connect 2 more floppies, then post a video. THANK YOU AGAIN!

**Comment by samphonic** [comment]
Haha, hooray!  I'm glad you got it working!

Thanks for the additional suggestions, @jazzbassNick, always helps to get some more angles on the issue.  =)
