### ISSUE TITLE
Different sound intensity on floppy drives

### ISSUE THREAD

**Issue by MarcAndreWyss** [samphonic/MoppyClassic#77]
Hi all

Well, it is not a question about the Moppy software itself, it is more a general question about the hardware setup.

I began to collect old 3.5'' floppies for my setup, but then i realized that some floppy drives are much louder than others. I was very sad about this issue because in my opinion all drives should play together as an (tuned up) orchestra. Therefore I bought 8 identical floppy drives on eBay. The serial numbers are all within a range of 27 (difference between highest and lowest serial number). They were born together and they play together. :-)

How did others solve this problem. Or am I the only one?

Thanks,
Marc

**Comment by MultiDaxio** [comment]
I have the same issue. It's preety annoying. That's why I'm giving the
weakes floppy the most not important notes and parts.

**Comment by samphonic** [comment]
Since there's no way to control the volume of the note the drives play, I used the drives' natural volume differences to my advantage when arranging music.  Quieter drives get the background parts so that the melody can be heard over them, and even then I often had to double up the melody.

I found you can also stick a floppy disk (if you can find one) into the drives to dampen the sound a bit.

I also found that at least with my drives, certain ranges of pitch were louder than others on the drive.  Usually the lower octaves were louder, so I would often try to get the melody down lower than the background parts.

**Comment by MarcAndreWyss** [comment]
I know that my solution is the expensive one, but I decided to take that one. I know myself, if something is not perfect, I will never stop thinking about it... :-)

**Comment by Solonn** [comment]
I have 8 floppies on my setup and just 3 of them are identical. The solution I found was the one already posted by SammyIAm (kudos for your work, man!); I use some midi tools to associate the most significant instruments to the louder floppies, and I'm very happy with the results. If you think of it, in an orchestra, the instruments play different parts so they can be used at their best.

**Comment by samphonic** [comment]
Doing some clean up.  This issue seems to be sufficiently resolved, and I've added the tips here to the [Wiki](https://github.com/SammyIAm/Moppy/wiki/FAQ)

**Comment by DigitallyRemastered** [comment]
A trick I have found to be most effective for emphasizing a specific melody part is to duplicate the track of interest and drop the pitch of its notes by an octave. Probably more of a psycho-acoustics thing if anything.
