### ISSUE TITLE
Moppy pooling feature seems to work very strangely.

### ISSUE THREAD

**Issue by ostrosablin** [samphonic/MoppyClassic#85]
I've experienced a problem. I have drive pooling set, but when I start Moppy, pooling won't work correctly.  For example, out of my 6 drives, only first one will play. What seems to fix it is unchecking drive pooling checkbox and setting strategy to straight-through and connecting, then disconnecting and setting drive pooling back on with Stacking strategy. This leads me to conclusion that Moppy doesn't correctly load and apply stored pooling settings. It's almost like they're reflected only in GUI, but have no actual effect. However, sometimes only replugging USB cable helps (while Moppy is running, but not connected). It feels that something is off, either with settings or with pooling itself.

**Comment by samphonic** [comment]
I will take a look at this when I get a chance.  In the meantime, at least there's a workaround.  :)

**Comment by AAllport** [comment]
what do the different drive pooling strategys mean?

**Comment by samphonic** [comment]
##### Straight Through

Does what you'd expect-- nothing.  Just passes the messages straight through.

##### Round Robin

Assigned each note to the next available a drive, searching in a round robin pattern.  That is, first note goes to first drive, second to second, etc.  If the next drive is still playing a note, it'll be skipped over.  If all the drives in the pool are currently playing notes and a new one comes in, it'll overwrite the note on the next drive.

##### Stack

Notes are assigned to the first available drive, searching from the first drive.  That is, the first note goes to the first drive, and if the first note stops before the second note starts, the second note will also play on the first drive.

**Comment by AAllport** [comment]
ok

**Comment by AAllport** [comment]
if there are no available drives and it is in stack will it overwrite any
notes?

**Comment by samphonic** [comment]
Hmm, looks like once it's full it'll just keep using the first drive over and over again.  You can see the actual code in the DrivePooler.java file.

**Comment by samphonic** [comment]
I fixed an issue with the sequencer that not only would have made performance pretty terribly, but also royally screwed up drive pooling.  As a result, pooling should work _much_ better now.

For the curious:
The getTransmitter() method on the Java MIDI sequencer object didn't return _the_ transmitter, it returned a brand-new transmitter each time.  Because I was using this method when connecting the sequencer to the drive pooler/drives, each time you pressed the "Connect" button, a duplicate transmitter was created.  With pooling turned off, this would result in a whole bunch of extra note messages being sent to the drives (potentially causing performance issues).  With pooling turned on, the pooler would attempt to play **all** of the notes, and things would get kind of hectic.  I only call that method once now, and things work a lot better.
