### ISSUE TITLE
Runtime Warning

### ISSUE THREAD

**Issue by knorke74** [samphonic/MoppyClassic#9]
I'm getting a warning when starting MoppyDesk in NetBeans:

```
org.jdesktop.application.LocalStorage getId
WARNUNG: unspecified resource Application.id using MoppyUI
```

Is this normal behaviour?

MoppyDeskwill start after that, but can only playback one tune, after that I would have to restart the Arduino and MoppyDesk. Could these two issues be related?

Using RXTX 2.2pre2 on Mac OS X 10.7.3

**Comment by knorke74** [comment]
I solved the restart issue. The method Serial.flush() has been changed in Arduino Software 1.0 and has to be replaced by for example

```
while(Serial.available() > 0){
        Serial.read();
      }
```

But I still get that runtime warning. Any ideas about that?

And, Sammy, thanks for all the work you put into this. It's a great project!

**Comment by samphonic** [comment]
Sorry about the lag.  First of all:

## Thank you so much!!

A whole bunch of people have started running into the restart issue and since I haven't recompiled my code, I haven't been able to reproduce it here.  Thank you, thank you.  I'll make a change to the code right now.

As far as the warning, it's nothing to be concerned about; I get it every time I start as well.  I think it's related to the Swing framework somehow and me not specifying some variables correctly (I don't use Swing much if you couldn't tell from the shoddy UI).  If you manage to figure out what it is, by all means submit a fix, but otherwise it shouldn't cause any trouble.
